site_name: Python Developer Roadmap
site_url: https://github.com/Dhruvish09/developer-roadmap
site_description: A comprehensive guide and roadmap for mastering Python, system design, DevOps, and interviews.
site_author: Dhruvish Patel
copyright: Copyright &copy; 2024 - 2027 Dhruvish Patel

theme:
  name: material
  logo: assets/images/Python_logo.png
  favicon: assets/images/3447021-removebg-preview.png
  palette:
    # Palette toggle for automatic mode
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Auto theme

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Light mode 
    # toggle:
    #   icon: material/toggle-switch-off-outline
    #   name: Switch between dark and light mode
  font:
    text: Roboto
    code: Fira Code
  icon:
    logo: material/puzzle-edit-outline
    # edit: material/pencil 
    # view: material/eye

  repo: fontawesome/brands/github
  custom_dir: docs/overrides

  # icon:
  #   previous: fontawesome/solid/angle-left
  #   next: fontawesome/solid/angle-right
  # logo:
  #   text: "Python Roadmap"
  #   image: 'images/logo.png'  # Path to the header logo image
  # favicon: 'images/logo1.png'
  features:
    - navigation.instant
    - navigation.tabs
    - toc.integrate
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tooltips
    - navigation.indexes
    - search.share
    # - content.action.edit
    # - navigation.footer
    # - header.autohide
  language: en

# theme:
#   name: material
#   # features:
#   #   - navigation.tabs
#   #   - navigation.sections  # This enables collapsible sections
#   palette:
#     primary: 'deep purple'
#     accent: 'amber'
#   font:
#     text: 'Roboto'
#     code: 'Roboto Mono'

# theme:
#   name: material
#   palette:
#     primary: 'blue'
#     accent: 'light blue'
#   font:
#     text: 'Open Sans'
#     code: 'Fira Mono'
  # logo: 'images/logo.png'

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.tasklist
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html

# markdown_extensions:
#   - toc:
#       permalink: true
#   - tables
#   - admonition
#   - codehilite:
#       guess_lang: false
#   - pymdownx.superfences

nav:
  - Home: index.md
  - Python:
    - OOPS:
        - Opps: Python/OOPS/Opps.md
        - Inheritance: Python/OOPS/Inheritance.md
    - Decorators: Python/Decorators.md
    - File Handling: Python/File_Handling.md
    - File I/O: Python/File_I_O.md
    - Generators & Iterators: Python/Generators_Iterators.md
    - Lambda & Functional: Python/Lambda_Functional_Programming.md
    - Memory Management: Python/Memory_Management.md
    - Parallel Programming: Python/Parallel_Programming.md
    - MetaProgramming: Python/MetaProgramming.md
    - Multithreading & Multiprocessing: Python/Multithreading_Multiprocessing.md
    - Celery: Python/Celery.md  
  - Database:
    - Redis: Database/redis.md
    - SQL:
      - Commands: Database/SQL/commands.md
      - Joins: Database/SQL/joins.md
      - Advanced SQL: Database/SQL/advanced_sql_topics.md
      - Indexing: Database/SQL/indexing.md
      - Normalization: Database/SQL/normalization.md
      - Query Optimization: Database/SQL/query_optimization.md
      - Sharding: Database/SQL/sharding.md
      - Store Procedure: Database/SQL/store_procedure.md
    - MONGODB:
      - Complete Topics: Database/MONGODB/complete_mongodb.md
      - Mongodb Practical: Database/MONGODB/mongodb_practical.md
  - ORM:
    - Django: ORM/django.md
    - Flask: ORM/flask.md
  - Interview:
    - Practical:
      - Data_type:
        - List:
          - Methods: Interview/Practical/Data_type/List/methods.md
          - Practical: Interview/Practical/Data_type/List/list_practical.md
        - String:
          - Methods: Interview/Practical/Data_type/String/methods.md
          - Practical: Interview/Practical/Data_type/String/string_practical.md
        - Dictionary:
          - Methods: Interview/Practical/Data_type/Dict/methods.md
      - SQL:
          - Commands: Interview/Practical/SQL/commands.md
          - practical: Interview/Practical/SQL/sql_practical.md
          - oral: Interview/Practical/SQL/sql_questions.md
    - ORAL_QA:
          - Python: Interview/Oral_Q_A.md/python.md
          - Sql: Interview/Oral_Q_A.md/sql.md
    - Problem Solve: Interview/problem_solve.md
  - Framework:
    - Django_Framework: Framework/Django_Framework.md
    - Flask_Framework: Framework/Flask_Framework.md
    - Fastapi_Framework: Framework/Fastapi_Framework.md

  - AI/ML :
    - Overview: AI_ML/overview.md
    - Langraph:
      - Overview: AI_ML/Langraph/overview.md
      - Agents: AI_ML/Langraph/Agents.md
      - Chains: AI_ML/Langraph/Chains.md
      - Memory: AI_ML/Langraph/Memory.md
      - Prompting: AI_ML/Langraph/Prompting.md
      - Tools: AI_ML/Langraph/Tools.md
      - Vectorstores: AI_ML/Langraph/Vectorstores.md
      - LLMs: AI_ML/Langraph/LLMs.md
      - Document Loaders: AI_ML/Langraph/Document_Loaders.md
      - Evaluation: AI_ML/Langraph/Evaluation.md
  - Devops:
    - Docker:
      - Docker: Devops/Docker/docker.md
      - Docker Compose: Devops/Docker/docker_compose.md
      - Kubernetes: Devops/Docker/kubernetes.md
    - AWS:
      - Overview: Devops/AWS/overview.md
    - Metrices: Devops/monitoring_observability.md

  - Roadmap:
    - Python:
      - Python Developer: Roadmap/Python/developer_roadmap.md

  - System Design:
      - Overview: System Design/overview.md
      - System Design Guide: 
          - System Design Process: System Design/System Design Guide/System Design Process.md
          - Request-Response: System Design/System Design Guide/Request-Response.md            
          - 30-Concepts-Cover-Project: System Design/System Design Guide/30_Concept_Cover_Project.md
          - E-Commerce: System Design/System Design Guide/E-Commerce.md
          - Most Ask System Design: System Design/System Design Guide/Most_Ask_System_Design.md

      - Core Concepts: 
          - Client-Server Model: System Design/Core Concepts/Client-Server Model.md
          - Stateless_Stateful: System Design/Core Concepts/Stateless_Stateful.md
          - Sync_Async Communication: System Design/Core Concepts/Sync_Async Communication.md
          - REST_RPC_GraphQL: System Design/Core Concepts/REST_RPC_GraphQL.md
          - Microservices_Monoliths: System Design/Core Concepts/Microservices_Monoliths.md
          - Service Discovery: System Design/Core Concepts/Service Discovery.md
          - Load Balancing: System Design/Core Concepts/Load Balancing.md

      - API Design & Gateways: 
          - API Specs: System Design/API Design & Gateways/API Specs.md
          - API Versioning: System Design/API Design & Gateways/API Versioning.md
          - API Gateway: System Design/API Design & Gateways/API Gateway.md
          - Circuit Breakers: System Design/API Design & Gateways/Circuit Breakers.md
          - Rate Limiting: System Design/API Design & Gateways/Rate Limiting_Auth.md

      - Design Patterns & Principles: 
          - 12Factor App: System Design/Design Patterns & Principles/12Factor App.md
          - Classic Patterns: System Design/Design Patterns & Principles/Classic Patterns.md
          - Dependency Injection: System Design/Design Patterns & Principles/Dependency Injection.md
          - Repository Pattern: System Design/Design Patterns & Principles/Repository Pattern.md
          - CQRS: System Design/Design Patterns & Principles/CQRS.md
          - Saga Pattern: System Design/Design Patterns & Principles/Saga Pattern.md
          - Event-driven Architecture: System Design/Design Patterns & Principles/Event-driven Architecture.md

      - Message Queues: 
          - Message Brokers: System Design/Message Queues & Async Processing/Message Brokers.md
          - Pub_Sub: System Design/Message Queues & Async Processing/Pub_Sub.md
          - Task Queues: System Design/Message Queues & Async Processing/Task Queues.md
          - Dead Letter Queues: System Design/Message Queues & Async Processing/Dead Letter Queues (DLQ).md

      - Distributed Systems: 
          - Consensus Algorithms: System Design/Distributed Systems Concepts/Consensus Algorithms.md
          - Leader Election: System Design/Distributed Systems Concepts/Leader Election.md
          - Quorum: System Design/Distributed Systems Concepts/Quorum.md
          - Logical Clocks: System Design/Distributed Systems Concepts/Logical Clocks.md
          - Distributed Locks: System Design/Distributed Systems Concepts/Distributed Locks.md

      - Data Management: 
          - SQL_NoSQL: System Design/Data Management/SQL_NoSQL.md
          - CAP Theorem: System Design/Data Management/CAP Theorem.md
          - Replication: System Design/Data Management/Replication.md
          - Eventual Consistency: System Design/Data Management/Eventual Consistency.md
          - Indexing_Query Optimization: System Design/Data Management/Indexing_Query Optimization.md
          - Caching Strategies: System Design/Data Management/Caching Strategies.md

      - Caching: 
          - Caching Tools: System Design/Caching/Caching Tools.md
          - CDN Edge Caching: System Design/Caching/CDN Edge Caching.md
          - Cache Invalidation: System Design/Caching/Cache Invalidation.md
          - Eviction Policies: System Design/Caching/Eviction Policies.md

      - Scalability: 
          - Horizontal_Vertical Scaling: System Design/Scalability/Horizontal_Vertical Scaling.md
          - Load Balancers: System Design/Scalability/Load Balancers.md
          - Sharding_Partitioning: System Design/Scalability/Sharding_Partitioning.md
          - Sticky Sessions: System Design/Scalability/Sticky Sessions.md
          - CDN: System Design/Scalability/CDN.md

      - High Availability: 
          - Redundancy: System Design/High Availability & Fault Tolerance/Redundancy.md
          - Health Checks: System Design/High Availability & Fault Tolerance/Health Checks.md
          - Failover Mechanisms: System Design/High Availability & Fault Tolerance/Failover Mechanisms.md
          - Auto Healing: System Design/High Availability & Fault Tolerance/Auto Healing.md
          - Graceful Degradation: System Design/High Availability & Fault Tolerance/Graceful Degradation.md

      - Security: 
          - Authentication: System Design/Security/Authentication.md
          - Authorization: System Design/Security/Authorization.md
          - Encryption: System Design/Security/Encryption.md
          - Transport Security: System Design/Security/Transport Security.md
          - Common Threats: System Design/Security/Common Threats.md
          - DDoS Protection: System Design/Security/DDoS Protection.md
          - Pre-SignedURL: System Design/Security/Pre-SignedUrl.md

      - System Performance: 
          - API Profiling_Benchmarking: System Design/System Performance & Optimization/API Profiling_Benchmarking.md
          - Backpressure Handling: System Design/System Performance & Optimization/Backpressure Handling.md
          - Bulkhead Pattern: System Design/System Performance & Optimization/Bulkhead Pattern.md
          - Rate Limiting_Throttling: System Design/System Performance & Optimization/Rate Limiting_Throttling.md

      - Observability: 
          - Logging: System Design/Observability/Logging.md
          - Monitoring: System Design/Observability/Monitoring.md
          - Alerting: System Design/Observability/Alerting.md
          - Tracing: System Design/Observability/Tracing.md

  - Communication:
    - Manager Round: Communication/Manger_Round.md

plugins:
  - offline
  - search
  - glightbox
  - minify:
      minify_html: true
  - redirects
  - git-revision-date-localized:
      type: timeago
      fallback_to_build_date: true

  # - mkdocs-git-revision-date-localized:
  #     type: git
  # - mkdocs-minify-plugin


# plugins:
#   - search
#   - mkdocs-git-revision-date-localized:
#       type: git
#   - mkdocs-minify-plugin

repo_url: https://github.com/Dhruvish09/developer-roadmap
repo_name: GitHub
edit_uri: edit/main/docs/
use_directory_urls: true

# extra_css:
#   - assets/css/custom.css

# extra_javascript:
#   - assets/js/custom.js

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics: Google Font
    actions:
      - accept
      - manage 
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Dhruvish09
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/dhruvish09/
      name: LinkedIn
    - icon: fontawesome/solid/paper-plane
      link: mailto:pateldhruvish612000@gmail.com
      name: Mail Me
    - icon: fontawesome/brands/twitter
      link: https://x.com/dhruvish09
      name: Twitter
  homepage: https://dhruvish09.github.io/developer-roadmap/index.html
  # scope: /

  # generator: false